RUN (4.000000): py "PythonSalesMan/main.py" DIJKSTRAQUEUE TestDijkstra\GrafPocConnectat100.GR Outputs\GrafPocConnectat100_DijkstraQueue.DIS
Nom Alumne 1.....: Cristina
Cognoms Alumne 1.: Huanca González
NIU Alumne 1.....: 1709896

Nom Alumne 2.....: Héctor
Cognoms Alumne 2.: Cervelló Navarro
NIU Alumne 2.....: 1708336

Algoritmo..: DIJKSTRAQUEUE
Grafo......: TestDijkstra\GrafPocConnectat100.GR
Distancias.: Outputs\GrafPocConnectat100_DijkstraQueue.DIS
Traceback (most recent call last):
  File "C:\Users\emmah\OneDrive\Escritorio\UNI\SEGON\2\DA\Salesman\GraphApplication\PythonSalesMan\main.py", line 32, in <module>
    if graph.CorrectionProcess(): sys.exit(0)
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emmah\OneDrive\Escritorio\UNI\SEGON\2\DA\Salesman\GraphApplication\PythonSalesMan\graph.py", line 272, in CorrectionProcess
    dijkstra.DijkstraQueue(g,start)
  File "C:\Users\emmah\OneDrive\Escritorio\UNI\SEGON\2\DA\Salesman\GraphApplication\PythonSalesMan\dijkstra.py", line 42, in DijkstraQueue
    start_vertex = g.GetVertex(start)
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Users\emmah\OneDrive\Escritorio\UNI\SEGON\2\DA\Salesman\GraphApplication\PythonSalesMan\graph.py", line 49, in GetVertex
    else: raise Exception('el vertex ', name,' no existeix')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: ('el vertex ', <graph.Vertex object at 0x000001E5F0CE7950>, ' no existeix')
TOTAL TIME=0.202527
